name: Our Steps
on: push
jobs:
  foobar:
    runs-on: ubuntu-latest
    steps:
      - id: set-foo
        run: echo "foo=bar" >> $GITHUB_OUTPUT
      - run: echo ${{ steps.set-foo.outputs.foo }}
  calculate:
    runs-on: ubuntu-latest
    steps:
      - id: gen-num1
        run: echo "num=$(($RANDOM % 10 + 1))" >> "$GITHUB_OUTPUT"
      - id: gen-num2
        run: echo "num=$(($RANDOM % 10 + 1))" >> "$GITHUB_OUTPUT"
      - run: echo $((${{ steps.gen-num1.outputs.num }} + ${{ steps.gen-num2.outputs.num }}))
      - run: echo $((${{ steps.gen-num1.outputs.num }} - ${{ steps.gen-num2.outputs.num }}))
      - run: echo $((${{ steps.gen-num1.outputs.num }} * ${{ steps.gen-num2.outputs.num }}))
      - run: echo $((${{ steps.gen-num1.outputs.num }} / ${{ steps.gen-num2.outputs.num }}))
  zeroone:
    runs-on: ubuntu-latest
    steps:
      - id: gen-num
        run: echo "num=$(($RANDOM % 2))" >> "$GITHUB_OUTPUT"
      - if: steps.gen-num.outputs.num == 0
        run: echo zero
      - if: steps.gen-num.outputs.num == 1
        run: echo one
  ignore:
    runs-on: ubuntu-latest
    steps:
      - id: flaky
        continue-on-error: true
        run: exit 1
      - run: echo "I don't care!"
  notify:
    runs-on: ubuntu-latest
    steps:
      - id: random
        run: exit $(($RANDOM % 2 == 0))
      - if: always()
        run: echo ${{ steps.random.outcome }}
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: original
        run: exit 1
      - name: backup
        if: failure()
        run: echo backup
